kind: Service
apiVersion: v1
metadata:
  name: service-config
  labels:
    app: service-config
spec:
  selector:
    app: service-config
  ports:
  - name: http
    port: 8888
    targetPort: 8888
  type: LoadBalancer


