kind: Service
apiVersion: v1
metadata:
  name: service-user
  labels:
    app: service-user
spec:
  selector:
    app: service-user
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: LoadBalancer


