apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        rewrite name regex (.*)\.serverconfig\.com serverconfig.com/\1
        forward . 10.108.96.246
    }
